/**
 * seedData.js
 * ============================================================================
 * Initial subjects seed data for the Vision Platform.
 * These are seeded into Firestore once on first admin visit.
 * Lessons are created separately via YouTube playlist sync.
 * ============================================================================
 */

export const INITIAL_SUBJECTS = [

  // ─────────────────────────────────────────────────────────────
  // الصف الأول الثانوي — المواد الأساسية المشتركة
  // ─────────────────────────────────────────────────────────────
  {
    id: 'g1-arabic',
    name: 'اللغة العربية',
    grade: 'grade-1',
    track: 'common',
    specialization: null,
    contentType: 'playlist',
    playlistUrl: 'https://youtube.com/playlist?list=PL5oLG_oU5VxFH5RY-zITHsgwOrxNvREws',
    description: 'منهج اللغة العربية للصف الأول الثانوي — النحو والصرف والأدب والبلاغة',
    teacher: 'فريق رؤية التعليمي',
    color: '#c084fc',
    glow: 'rgba(192, 132, 252, 0.3)',
    icon: 'BookOpen',
    order: 1,
    published: true,
    syncedAt: null,
    lessonsCount: 0,
  },
  {
    id: 'g1-english',
    name: 'اللغة الإنجليزية',
    grade: 'grade-1',
    track: 'common',
    specialization: null,
    contentType: 'playlist',
    playlistUrl: 'https://youtube.com/playlist?list=PLchtCcAAGA9Byku-xURt8TxREtkIqCzXi',
    description: 'منهج اللغة الإنجليزية للصف الأول الثانوي — القواعد والمحادثة والقراءة',
    teacher: 'فريق رؤية التعليمي',
    color: '#38bdf8',
    glow: 'rgba(56, 189, 248, 0.3)',
    icon: 'Globe',
    order: 2,
    published: true,
    syncedAt: null,
    lessonsCount: 0,
  },
  {
    id: 'g1-history',
    name: 'التاريخ',
    grade: 'grade-1',
    track: 'common',
    specialization: null,
    contentType: 'playlist',
    playlistUrl: 'https://youtube.com/playlist?list=PLNZylwdJLcQmlT3xE4kIoy4cpM-wbIL0t',
    description: 'منهج التاريخ للصف الأول الثانوي — الحضارات والتاريخ المعاصر',
    teacher: 'فريق رؤية التعليمي',
    color: '#fbbf24',
    glow: 'rgba(251, 191, 36, 0.3)',
    icon: 'ScrollText',
    order: 3,
    published: true,
    syncedAt: null,
    lessonsCount: 0,
  },
  {
    id: 'g1-math',
    name: 'الرياضيات',
    grade: 'grade-1',
    track: 'common',
    specialization: null,
    contentType: 'playlist',
    playlistUrl: 'https://youtube.com/playlist?list=PLYGJU1U6eacOlCZjwMj5UjloWypBtlnu0',
    description: 'منهج الرياضيات للصف الأول الثانوي — الجبر والهندسة والإحصاء',
    teacher: 'فريق رؤية التعليمي',
    color: '#f43f5e',
    glow: 'rgba(244, 63, 94, 0.3)',
    icon: 'Calculator',
    order: 4,
    published: true,
    syncedAt: null,
    lessonsCount: 0,
  },
  {
    id: 'g1-science',
    name: 'العلوم المتكاملة',
    grade: 'grade-1',
    track: 'common',
    specialization: null,
    contentType: 'playlist',
    playlistUrl: 'https://youtube.com/playlist?list=PL5oLG_oU5VxFH5RY-zITHsgwOrxNvREws',
    description: 'منهج العلوم المتكاملة للصف الأول الثانوي — الأحياء والكيمياء والفيزياء',
    teacher: 'فريق رؤية التعليمي',
    color: '#00e676',
    glow: 'rgba(0, 230, 118, 0.3)',
    icon: 'Atom',
    order: 5,
    published: true,
    syncedAt: null,
    lessonsCount: 0,
  },
  {
    id: 'g1-philosophy',
    name: 'الفلسفة والمنطق',
    grade: 'grade-1',
    track: 'common',
    specialization: null,
    contentType: 'playlist',
    playlistUrl: 'https://youtube.com/playlist?list=PLtiC5L61P7PqWW-q0fDdOR1BOH3qVFRVj',
    description: 'منهج الفلسفة والمنطق للصف الأول الثانوي — التفكير النقدي والفلسفة المعاصرة',
    teacher: 'فريق رؤية التعليمي',
    color: '#a78bfa',
    glow: 'rgba(167, 139, 250, 0.3)',
    icon: 'Brain',
    order: 6,
    published: true,
    syncedAt: null,
    lessonsCount: 0,
  },

  // ─────────────────────────────────────────────────────────────
  // الصف الثاني الثانوي (البكالوريا) — المواد الأساسية المشتركة
  // ─────────────────────────────────────────────────────────────
  {
    id: 'g2-arabic',
    name: 'اللغة العربية',
    grade: 'grade-2',
    track: 'common',
    specialization: null,
    contentType: 'playlist',
    playlistUrl: 'https://youtube.com/playlist?list=PLBsxNqayvozqrIN4SM9l55JxYOjg1AbZJ',
    description: 'منهج اللغة العربية للصف الثاني الثانوي (البكالوريا)',
    teacher: 'فريق رؤية التعليمي',
    color: '#c084fc',
    glow: 'rgba(192, 132, 252, 0.3)',
    icon: 'BookOpen',
    order: 1,
    published: true,
    syncedAt: null,
    lessonsCount: 0,
  },
  {
    id: 'g2-english',
    name: 'اللغة الإنجليزية',
    grade: 'grade-2',
    track: 'common',
    specialization: null,
    contentType: 'playlist',
    playlistUrl: 'https://youtube.com/playlist?list=PLcnhTg3Redx3GVZKJp9wHHuxWhQTht575',
    description: 'منهج اللغة الإنجليزية للصف الثاني الثانوي',
    teacher: 'فريق رؤية التعليمي',
    color: '#38bdf8',
    glow: 'rgba(56, 189, 248, 0.3)',
    icon: 'Globe',
    order: 2,
    published: true,
    syncedAt: null,
    lessonsCount: 0,
  },
  {
    id: 'g2-history',
    name: 'التاريخ',
    grade: 'grade-2',
    track: 'common',
    specialization: null,
    contentType: 'video',
    playlistUrl: 'https://youtu.be/9zPtc1SWQFU',
    description: 'منهج التاريخ للصف الثاني الثانوي',
    teacher: 'فريق رؤية التعليمي',
    color: '#fbbf24',
    glow: 'rgba(251, 191, 36, 0.3)',
    icon: 'ScrollText',
    order: 3,
    published: true,
    syncedAt: null,
    lessonsCount: 0,
  },

  // ─────────────────────────────────────────────────────────────
  // مسار الطب وعلوم الحياة
  // ─────────────────────────────────────────────────────────────
  {
    id: 'med-chemistry',
    name: 'الكيمياء',
    grade: null,
    track: 'medicine',
    specialization: null,
    contentType: 'playlist',
    playlistUrl: 'https://youtube.com/playlist?list=PL53PAzy1H_o0bm-xevUSVTDUm-6ThEIyz',
    description: 'منهج الكيمياء لمسار الطب وعلوم الحياة — الكيمياء العضوية وغير العضوية',
    teacher: 'فريق رؤية التعليمي',
    color: '#00e676',
    glow: 'rgba(0, 230, 118, 0.3)',
    icon: 'FlaskConical',
    order: 1,
    published: true,
    syncedAt: null,
    lessonsCount: 0,
  },
  {
    id: 'med-physics',
    name: 'الفيزياء',
    grade: null,
    track: 'medicine',
    specialization: null,
    contentType: 'video',
    playlistUrl: 'https://youtu.be/I9YMhR9K_g8',
    description: 'منهج الفيزياء لمسار الطب وعلوم الحياة — الفيزياء الطبية والموجات',
    teacher: 'فريق رؤية التعليمي',
    color: '#fbbf24',
    glow: 'rgba(251, 191, 36, 0.3)',
    icon: 'Zap',
    order: 2,
    published: true,
    syncedAt: null,
    lessonsCount: 0,
  },

  // ─────────────────────────────────────────────────────────────
  // مسار الهندسة وعلوم الحاسب
  // ─────────────────────────────────────────────────────────────
  {
    id: 'eng-programming',
    name: 'البرمجة',
    grade: null,
    track: 'engineering',
    specialization: null,
    contentType: 'playlist',
    playlistUrl: 'https://youtube.com/playlist?list=PLvGNfY-tFUN_1D3D0WAMlWULl3qnEKHEA',
    description: 'منهج البرمجة لمسار الهندسة وعلوم الحاسب — أساسيات البرمجة والخوارزميات',
    teacher: 'فريق رؤية التعليمي',
    color: '#00e676',
    glow: 'rgba(0, 230, 118, 0.3)',
    icon: 'Code2',
    order: 1,
    published: true,
    syncedAt: null,
    lessonsCount: 0,
  },
  {
    id: 'eng-math',
    name: 'الرياضيات المتقدمة',
    grade: null,
    track: 'engineering',
    specialization: null,
    contentType: 'video',
    playlistUrl: 'https://youtu.be/n53-PPtsfOE',
    description: 'منهج الرياضيات المتقدمة لمسار الهندسة — التفاضل والتكامل والجبر الخطي',
    teacher: 'فريق رؤية التعليمي',
    color: '#38bdf8',
    glow: 'rgba(56, 189, 248, 0.3)',
    icon: 'Calculator',
    order: 2,
    published: true,
    syncedAt: null,
    lessonsCount: 0,
  },
];

/** Sentinel document ID — prevents re-seeding on subsequent app loads */
export const SEED_SENTINEL_ID = '__seed_v1__';
