import {
  Dna,
  Atom,
  Zap,
  BookOpen,
  Calculator,
  Code2,
  Brain,
  Globe,
  Palette,
  Briefcase,
  TrendingUp,
  Receipt,
  FileSpreadsheet,
  Languages,
  ScrollText
} from 'lucide-react';

/**
 * Dynamic subject configuration mapped per educational path.
 */
export const PATH_SUBJECTS_CONFIG = {
  medicine: [
    {
      id: 'biology',
      title: 'الأحياء والوراثة',
      description: 'دراسة الخلية، الحمض النووي (DNA)، ووظائف الأعضاء في الكائنات الحية.',
      lessonsCount: 24,
      progress: 75,
      icon: Dna,
      color: '#00e676',
      glow: 'rgba(0, 230, 118, 0.3)',
      accent: 'rgba(0, 230, 118, 0.1)',
    },
    {
      id: 'chemistry',
      title: 'الكيمياء الحيوية',
      description: 'الكيمياء العضوية، التفاعلات الكيميائية وتطبيقاتها في مجال الطب.',
      lessonsCount: 20,
      progress: 60,
      icon: Atom,
      color: '#38bdf8',
      glow: 'rgba(56, 189, 248, 0.3)',
      accent: 'rgba(56, 189, 248, 0.1)',
    },
    {
      id: 'physics',
      title: 'الفيزياء الطبية',
      description: 'الفيزياء الحديثة، الموجات وتطبيقات الأشعة في الأجهزة الطبية.',
      lessonsCount: 18,
      progress: 45,
      icon: Zap,
      color: '#fbbf24',
      glow: 'rgba(251, 191, 36, 0.3)',
      accent: 'rgba(251, 191, 36, 0.1)',
    },
    {
      id: 'arabic',
      title: 'اللغة العربية والبلاغة',
      description: 'النحو والتحليل اللغوي والأدب والنصوص لتعزيز مهارات التواصل.',
      lessonsCount: 16,
      progress: 90,
      icon: BookOpen,
      color: '#c084fc',
      glow: 'rgba(192, 132, 252, 0.3)',
      accent: 'rgba(192, 132, 252, 0.1)',
    },
    {
      id: 'english',
      title: 'اللغة الإنجليزية التخصصية',
      description: 'المصطلحات العلمية الطبية والقراءة الناقدة والكتابة الأكاديمية.',
      lessonsCount: 15,
      progress: 80,
      icon: Globe,
      color: '#f43f5e',
      glow: 'rgba(244, 63, 94, 0.3)',
      accent: 'rgba(244, 63, 94, 0.1)',
    },
  ],

  engineering: [
    {
      id: 'math',
      title: 'الرياضيات التطبيقية والهندسة',
      description: 'التفاضل والتكامل، الجبر الخطي والهندسة الفراغية.',
      lessonsCount: 30,
      progress: 65,
      icon: Calculator,
      color: '#38bdf8',
      glow: 'rgba(56, 189, 248, 0.3)',
      accent: 'rgba(56, 189, 248, 0.1)',
    },
    {
      id: 'programming',
      title: 'البرمجة وهياكل البيانات',
      description: 'أساسيات البرمجة بلغة الخوارزميات والتفكير البرمجي المنطقي.',
      lessonsCount: 22,
      progress: 85,
      icon: Code2,
      color: '#00e676',
      glow: 'rgba(0, 230, 118, 0.3)',
      accent: 'rgba(0, 230, 118, 0.1)',
    },
    {
      id: 'physics',
      title: 'الفيزياء العامة والكهرباء',
      description: 'الميكانيكا، الكهربية والمغناطيسية والدوائر الإلكترونية.',
      lessonsCount: 22,
      progress: 50,
      icon: Zap,
      color: '#fbbf24',
      glow: 'rgba(251, 191, 36, 0.3)',
      accent: 'rgba(251, 191, 36, 0.1)',
    },
    {
      id: 'chemistry',
      title: 'الكيمياء الهندسية',
      description: 'كيمياء المواد، الروابط وتحليلات التفاعلات الكيميائية.',
      lessonsCount: 18,
      progress: 40,
      icon: Atom,
      color: '#c084fc',
      glow: 'rgba(192, 132, 252, 0.3)',
      accent: 'rgba(192, 132, 252, 0.1)',
    },
    {
      id: 'english',
      title: 'اللغة الإنجليزية الهندسية',
      description: 'المصطلحات التقنية والكتابة الفنية والمصطلحات البرمجية.',
      lessonsCount: 14,
      progress: 70,
      icon: Globe,
      color: '#f43f5e',
      glow: 'rgba(244, 63, 94, 0.3)',
      accent: 'rgba(244, 63, 94, 0.1)',
    },
  ],

  arts: [
    {
      id: 'psychology',
      title: 'علم النفس والاجتماع',
      description: 'دراسة السلوك الإنساني، النمو، والتفاعل الاجتماعي والتفكير التظليلي.',
      lessonsCount: 18,
      progress: 88,
      icon: Brain,
      color: '#c084fc',
      glow: 'rgba(192, 132, 252, 0.3)',
      accent: 'rgba(192, 132, 252, 0.1)',
    },
    {
      id: 'history',
      title: 'التاريخ والحضارات',
      description: 'دراسة التطور الحضاري والتاريخ المعاصر والتحليل النقدي للأحداث.',
      lessonsCount: 20,
      progress: 60,
      icon: ScrollText,
      color: '#fbbf24',
      glow: 'rgba(251, 191, 36, 0.3)',
      accent: 'rgba(251, 191, 36, 0.1)',
    },
    {
      id: 'second-lang',
      title: 'اللغة الأجنبية الثانية',
      description: 'إتقان مهارات الاستماع والتحدث وقواعد اللغة المختارة.',
      lessonsCount: 16,
      progress: 75,
      icon: Languages,
      color: '#00e676',
      glow: 'rgba(0, 230, 118, 0.3)',
      accent: 'rgba(0, 230, 118, 0.1)',
    },
    {
      id: 'media-arts',
      title: 'الفنون والإعلام الرقمي',
      description: 'مهارات التصميم، النقد الفني، والإعلام الحديث وصناعة المحتوى.',
      lessonsCount: 15,
      progress: 95,
      icon: Palette,
      color: '#38bdf8',
      glow: 'rgba(56, 189, 248, 0.3)',
      accent: 'rgba(56, 189, 248, 0.1)',
    },
  ],

  business: [
    {
      id: 'accounting',
      title: 'المحاسبة المالية',
      description: 'إعداد الدفاتر وقوائم الدخل والميزانية وتتبع المصروفات.',
      lessonsCount: 22,
      progress: 80,
      icon: Receipt,
      color: '#fbbf24',
      glow: 'rgba(251, 191, 36, 0.3)',
      accent: 'rgba(251, 191, 36, 0.1)',
    },
    {
      id: 'management',
      title: 'إدارة الأعمال وريادة الأعمال',
      description: 'التخطيط الاستراتيجي، قيادة فرق العمل وتأسيس المشاريع الناجحة.',
      lessonsCount: 20,
      progress: 70,
      icon: Briefcase,
      color: '#00e676',
      glow: 'rgba(0, 230, 118, 0.3)',
      accent: 'rgba(0, 230, 118, 0.1)',
    },
    {
      id: 'economics',
      title: 'الاقتصاد والإحصاء التجاري',
      description: 'مبادئ العرض والطلب، التحليل المالي، والإحصاء التطبيقي.',
      lessonsCount: 18,
      progress: 55,
      icon: TrendingUp,
      color: '#38bdf8',
      glow: 'rgba(56, 189, 248, 0.3)',
      accent: 'rgba(56, 189, 248, 0.1)',
    },
    {
      id: 'business-english',
      title: 'اللغة الإنجليزية للأعمال',
      description: 'كتابة التقارير المالية والخطابات التجارية ومهارات العرض.',
      lessonsCount: 14,
      progress: 85,
      icon: FileSpreadsheet,
      color: '#c084fc',
      glow: 'rgba(192, 132, 252, 0.3)',
      accent: 'rgba(192, 132, 252, 0.1)',
    },
  ],
};
